[package]
name = "helloworld"
version = "0.1.0"
edition.workspace = true

[dependencies]
sparreal-rt = { workspace = true, features = [
    "early-print",
]}
# sparreal-kernel = { workspace = true }
log = { workspace = true }
